<a href="https://colab.research.google.com/github/Vaishnavi943/ML_Project/blob/main/Emotion_Detection_with_NLP_%26_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Emotion Detection with NLP & ML**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!unzip /content/train.txt.zip -d /content/

Archive:  /content/train.txt.zip
  inflating: /content/train.txt

In [3]:
df = pd.read_csv('/content/train.txt', sep=';', names=['text', 'emotion'], header=None)
print(df.head())

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

Text cleaning & pre processing

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [7]:
unique_emotion = df['emotion'].unique()
emotion_numbers = {}
i=0
for emotion in unique_emotion:
  emotion_numbers[emotion] = i
  i+=1
print(emotion_numbers)

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [8]:
df['text'] = df['text'].apply(lambda x: x.lower())
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

In [9]:
import string

def remove_punctuation(text):
  for punctuation in string.punctuation:
    text = text.replace(punctuation, '')
  return text

In [10]:
def remove_numbers(text):
  for number in range(10):
    text = text.replace(str(number), '')
  return text

In [11]:
def remove_url_links(text):
  url = re.compile(r'https?://\S+|www\.\S+')
  return url.sub(r'', text)

In [12]:
import re

def remove_html_tag(text):
  html = re.compile(r'<.*?>')
  return html.sub(r'', text)

In [13]:
def remove_emoji(text):
  new = ""
  for i in text:
    if i.isascii():
      new+=i
  return new

df['text'] = df['text'].apply(remove_emoji)
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

In [16]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [17]:
def remove_stopwords(text):
  word_tokens = word_tokenize(text)
  cleaned_text = []
  for i in word_tokens:
    if i not in stop_words:
      cleaned_text.append(i)
  return ' '.join(cleaned_text)

df['text'] = df['text'].apply(remove_stopwords)

In [19]:
df.loc[1, 'text']

'go feeling hopeless damned hopeful around someone cares awake'